# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    expose:
      - '3306'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'learn-batch'
      MYSQL_ROOT_HOST: '%'

  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"  # passive ports
    environment:
      FTP_USER_NAME: demo
      FTP_USER_PASS: demo123
      FTP_USER_HOME: /home/demo
    volumes:
      - ./ftp-data:/home/demo  # local folder maps to FTP user home

  rabbitmq:
    image: rabbitmq:3.13-management   # includes the web UI
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # management UI http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest