# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    expose:
      - '3306'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'learn-batch'
      MYSQL_ROOT_HOST: '%'